# Generated by Django 4.2.1 on 2023-05-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigIntegerField(editable=False, primary_key=True, serialize=False)),
                ('student_id', models.BigIntegerField(editable=False)),
                ('signature', models.CharField(max_length=512)),
            ],
        ),
    ]
