# Generated by Django 4.2.1 on 2023-05-21 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('validate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='transcript',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='signature',
            field=models.CharField(editable=False, max_length=512),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='student_id',
            field=models.BigIntegerField(),
        ),
        migrations.CreateModel(
            name='SubjectInTranscript',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validate.subject')),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validate.transcript')),
            ],
        ),
    ]
