# Generated by Django 4.2.1 on 2023-05-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validate', '0002_subject_transcript_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.BigAutoField(editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
