# Generated by Django 4.2.1 on 2023-05-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validate', '0003_alter_subject_id_alter_transcript_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
