# Generated by Django 4.2.1 on 2023-05-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validate', '0004_alter_subject_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
