# Generated by Django 4.2.1 on 2023-05-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validate', '0006_remove_subject_subject_code_alter_subject_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='subjects',
            field=models.ManyToManyField(through='validate.SubjectInTranscript', to='validate.subject'),
        ),
    ]
