# Generated by Django 4.2.1 on 2023-05-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validate', '0007_transcript_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectintranscript',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
