# Generated by Django 4.2.1 on 2023-05-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validate', '0008_alter_subjectintranscript_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectintranscript',
            name='grade',
            field=models.CharField(default='A', max_length=2),
        ),
        migrations.AddField(
            model_name='subjectintranscript',
            name='marks',
            field=models.BigIntegerField(default=0),
        ),
    ]
