# Generated by Django 4.2.1 on 2023-05-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validate', '0011_rename_student_id_transcript_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='storage',
            field=models.FileField(null=True, upload_to='transcripts'),
        ),
    ]
